schema = 3

[mod]
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
  [mod."github.com/gdamore/encoding"]
    version = "v1.0.0"
    hash = "sha256-aV6wbQTwdOBHXMqWbhIxQ6YLun+gY6lIdSKKROkvte4="
  [mod."github.com/gdamore/tcell/v2"]
    version = "v2.6.0"
    hash = "sha256-4hnWoGV4CkvuTTuro/lCrLjSYDOQ/kRJb9hZ+lCERgQ="
  [mod."github.com/ktr0731/go-ansisgr"]
    version = "v0.1.0"
    hash = "sha256-MTBJ3fxu6CQrND7dO9xwFHfFuq7PllQsgfDTh2caVsI="
  [mod."github.com/ktr0731/go-fuzzyfinder"]
    version = "v0.8.0"
    hash = "sha256-P/QNhs+9z2EIyQJaO6flGaZtD2G05ZMABaNiEkv4Gq0="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.15"
    hash = "sha256-WP39EU2UrQbByYfnwrkBDoKN7xzXsBssDq3pNryBGm0="
  [mod."github.com/nfx/go-htmltable"]
    version = "v0.4.0"
    hash = "sha256-BBefB2gEsRpIp7WpKk4Dn51tymNSfu3TUP+pwSh/L9Y="
  [mod."github.com/nsf/termbox-go"]
    version = "v1.1.1"
    hash = "sha256-Fxk9s3vKmXO3uWmpneN1iZQ+nCbUEZLWShDyeJcwhvM="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.3"
    hash = "sha256-cFs6l3HsBpx1Rqf8pik+zMFDgFyvaF+MTjbxlNKKvZA="
  [mod."golang.design/x/clipboard"]
    version = "v0.7.0"
    hash = "sha256-8nLafFDR8ZT+cVS1OP0Ga5sfxBEU0jqJfEsaopqAJQg="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20190731235908-ec7cb31e5a56"
    hash = "sha256-yCZV3BVAEWvanA4QkhRMcNHtOV7DGKr9ltRR3zSmjaI="
  [mod."golang.org/x/image"]
    version = "v0.6.0"
    hash = "sha256-fZc2Jfh6EqsjmMBUMaGHn8+bSMetuZ7K4AxU8BRXt94="
  [mod."golang.org/x/mobile"]
    version = "v0.0.0-20230301163155-e0f57694e12c"
    hash = "sha256-tzfN+jS8U1XeLm1xPO3CvG9zgwf8aegkyOe2BMqHDBU="
  [mod."golang.org/x/net"]
    version = "v0.6.0"
    hash = "sha256-e8F4kMogxT392mmimvcAmkUtD/5vcQRPWDwH238m8FU="
  [mod."golang.org/x/sys"]
    version = "v0.14.0"
    hash = "sha256-ReIRQmONicRW9idzGVPCBx5TTcKacmQTF1vPC3L4SxY="
  [mod."golang.org/x/term"]
    version = "v0.5.0"
    hash = "sha256-f3DiX7NkDsEZpPS+PbmnOH9F5WHFZ1sQrfFg/T2UPno="
  [mod."golang.org/x/text"]
    version = "v0.8.0"
    hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="
